theme: jekyll-theme-minimal

title: HUI bike - a bike magnet sensor adaption board
description: A small ATtiny based bike magnet RPM sensor adaption board.
logo: https://github.com/eurovibes/huibike/raw/master/images/huibike.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
